Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
data=load_iris()
#1.Extract feature matrix as NumPy array
x=data.data


#2.Compute: Mean Median Standard deviation Variance (for each feature)
mean=np.mean(x,axis=0)
median=np.median(x,axis=0)
standard_variation=np.std(x,axis=0)
var=np.var(x,axis=0)

#3.Identify: Which feature has highest variability and why it matters in ML

highest_variability=np.argmax(var)
print(highest_variability)
#why it matters in ML:Because it gives more information

#4.Convert any one feature into shape (n,1) and explain why ML models expect this format

feature=x[:,0]
print(feature.shape)
reshape=feature.reshape(-1,1)
print(reshape.shape)


why ML models expect this format:ML model always reshape single feature,because ml model need 2D input

2
(150,)
(150, 1)

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [8]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
X = iris.data

# First 100 samples, last 2 features
X_subset = X[:100, 2:]

#print(X_subset.shape)


#2.Use boolean masking: Select samples where petal length is greater than dataset mean
petal_length=X[:,2]
mean=np.mean(petal_length)
mask=petal_length>mean
samples_selected=X[mask]
#print(samples_selected)

#3.Count selected samples
count_0f_selected_samples=np.sum(mask) 
#print(count_0f_selected_samples)

#4.Explain how this relates to feature-based filtering in ML

#It help to filter the useful samples beacause some data may not help the model.If we filter it will help the modellearn better.

93

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1.Apply standardization:
    
 
2.                                         

Verify: Mean ≈ 0 Std ≈ on

In [14]:
from sklearn.datasets import load_iris
import numpy as np
data=load_iris()
x=data.data

#1.Verify: Mean ≈ 0 Std ≈ on

mean=np.mean(x,axis=0)
std=np.std(x,axis=0)

#2.Apply standardization:

standardization=(x-mean)/std
#print(standardization)

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [15]:
import seaborn as sns
#1.Display: head(), tail() info(), describe()df.head()
df=sns.load_dataset("titanic")
df.head()
df.tail()
df.info()
df.describe()


#2.Identify: Missing values per column Numerical vs categorical features

df.isna().sum()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [26]:
import seaborn as sns
import pandas as pd
df=sns.load_dataset("titanic")

#1.Female passengers in 1st class

female_first_class = df[(df['sex'] == 'female') & (df['class'] == 'First')]
#print(female_first_class)

#2.Survival rate for this group
group_survival_rate = female_first_class['survived'].mean()
#print(group_survival_rate)

#3.over all survival rate
over_all_survivalrate=df["survived"].mean()
print(over_all_survivalrate)

#4.insight=Female passengers in 1st class had a much higher survival rate compared to the overall population

0.3838383838383838

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [34]:
import seaborn as sns
import pandas as pd
df=sns.load_dataset("titanic")

#1Fil.l missing age using median

df['age'].fillna (df['age'].median(),inplace=True)

#2.Fill missing embarked using mode

df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)

#3.Drop deck column
df.drop(coloumn=['deck'],inplace=True)

#4.Why different strategies are used for different columns

#age is numerical so median is more stable,embarked is categorical here values are labels,and drop coulmn we are using when there are somany missing values.If we filling the missing values it may introduce wrong information it is better to remove than meslead label

C:\Users\giree\AppData\Local\Temp\ipykernel_28248\3034130874.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna (df['age'].median(),inplace=True)
C:\Users\giree\AppData\Local\Temp\ipykernel_28248\3034130874.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode(),inplace=True)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [39]:
import seaborn as sns
import pandas as pd

df=sns.load_dataset("titanic")
#1.Create: family_size = sibsp + parch + 1
df.family_size = df["sibsp"] + df["parch"] + 1
#df.head()

#2.Create: is_alone (binary feature)

df['is_alone'] = (df['family_size'] == 1).astype(int)


#3.Compute survival rate by is_alone

survival_by_alone = df.groupby('is_alone')['survived'].mean()
print(survival_by_alone)

C:\Users\giree\AppData\Local\Temp\ipykernel_28248\623678181.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.family_size = df["sibsp"] + df["parch"] + 1

KeyError: 'family_size'

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [65]:
import seaborn as sns
import pandas as pd

df=sns.load_dataset("tips")
df.head()

#1.Compute: Average tip by day Total bill by gender

average_tip_byday=df.groupby("day")['tip'].mean()
#print(average_tip_byday)

totalbill_by_gender=df.groupby('sex')['total_bill'].sum()


#print(totalbill_by_gender)

#2.Create new feature: tip_percentage
df['tip_percentage']=(df['tip'] / df['total_bill'])*100

#print(df['tip_percentage'])

#3.Identify: Which day has highest tipping behavior

tip_percentage_by_day=df.groupby("day")['tip_percentage'].mean()
#print(tip_percentage_by_day)

highest_day=tip_percentage_by_day.idxmax()
print(highest_day)

#4.How this helps in segmentation models
Because they reveals patterns in customer behaviour

Fri

C:\Users\giree\AppData\Local\Temp\ipykernel_28248\2769128045.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_tip_byday=df.groupby("day")['tip'].mean()
C:\Users\giree\AppData\Local\Temp\ipykernel_28248\2769128045.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  totalbill_by_gender=df.groupby('sex')['total_bill'].sum()
C:\Users\giree\AppData\Local\Temp\ipykernel_28248\2769128045.py:24: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tip_percentage_by_day=df.groupby("day")['tip_percentage'].mean()

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [76]:
import seaborn as sns
import pandas as pd

df=sns.load_dataset("tips")
df.head()

#Filter: total_bill > 20 AND tip < 3
Filter=df[(df['total_bill'] > 20) & (df['tip'] < 3)]
print(Filter) 

#Select only relevant columns

relevant_column=filter[['total_bill','tip']]
print(relevant_column)

#Analyze: Is this segment under-tipping?

Filter['tip_percentage'] = (Filter['tip'] / Filter['total_bill']) * 100

print(Filter['tip_percentage'].mean())
print(df['tip'].mean() / df['total_bill'].mean() * 100)

yes

#5ain: How such filtering helps anomaly detection


#it will help to find unusual data like high bill with less tip .So the model can learn this behaviour detect easly

     total_bill   tip     sex smoker   day    time  size
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
48        28.55  2.05    Male     No   Sun  Dinner     3
57        26.41  1.50  Female     No   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
113       23.95  2.55    Male     No   Sun  Dinner     2
119       24.08  2.92  Female     No  Thur   Lunch     4
129       22.82  2.18    Male     No  Thur   Lunch     3
131       20.27  2.83  Female     No  Thur   Lunch     2
153       24.55  2.00    Male     No   Sun  Dinner     4
166       20.76  2.24    Male     No   Sun  Dinner     2
187       30.46  2.00    Male    Yes   Sun  Dinner     5
192       28.44  2.56    Male    Yes  Thur   Lunch     2
208       24.27  2.03    Male    Yes   Sat  Dinner     2
210       30.06  2.00    Male    Yes   Sat  Dinner     3
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
237       32.83  1.17    Male    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2

TypeError: type 'filter' is not subscriptable

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [82]:
import numpy as np
#Create two arrays of shape (3,2)
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[7,8],[9,10],[11,12]])

print(a.shape)
print(b.shape)

#Perform: Vertical stacking Horizontal stacking

v=np.vstack((a,b))
h=np.hstack((a,b))
print(v)
print(h)

#Reshape into (2,6)

reshaped=v.reshape(2,6)
print(reshaped)


#Explain: Why reshaping is required in ML pipelines

to get the data in same structure as the ml model require.

(3, 2)
(3, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [84]:
import seaborn as sns
import pandas as pd
import numpy as np
df=sns.load_dataset("titanic")

#Handle missing values
df['age'].fillna(df['age'].median(), inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
df.drop(columns=['deck'], inplace=True)

#encode categorical variables (sex, embarked)
df = pd.get_dummies(df, columns=['sex', 'embarked'], drop_first=True)


#Convert to NumPy array
X = df.drop(columns=['survived']).values
y = df['survived'].values

print(X.shape)
print(y.shape)

(891, 14)
(891,)

C:\Users\giree\AppData\Local\Temp\ipykernel_28248\1721881241.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
C:\Users\giree\AppData\Local\Temp\ipykernel_28248\1721881241.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [ ]:
rom sklearn.datasets import load_iris
import pandas as pd

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [90]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset("titanic")
#Create age_group: Child / Adult / Senior

def agecategory(age):
    
    if age < 18:
        return "Child"
    elif age < 60:
        return "Adult"
    else:
        return "Senior"

df['age_group']=df['age'].apply(agecategory)
print(df['age_group'])

survival_by_group = df.groupby('age_group')['survived'].mean()
print(survival_by_group)

#Interpret: Which segment has highest survival likelihood
children

0       Adult
1       Adult
2       Adult
3       Adult
4       Adult
        ...
886     Adult
887     Adult
888    Senior
889     Adult
890     Adult
Name: age_group, Length: 891, dtype: object
age_group
Adult     0.386087
Child     0.539823
Senior    0.290640
Name: survived, dtype: float64

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [94]:
import numpy as np
#Generate 1000 random error values using NumPy

errorvalue=np.random.randn(10000)
mean=np.mean(errorvalue)
std=np.std(errorvalue)
print(mean)
print(std)

#Identify outliers: Using mean ± 2*std

upper=mean-2*std
lower=mean+2*std
outliers=errorvalue[(errorvalue<lower)|(errorvalue>upper)]
print(outliers)

Explain: What high variance means in model performance

High variance means the model’s errors vary widely, indicating unstable predictions and poor generalization (overfitting)

-0.007244093259008188
1.000360272988083
[ 0.16023658 -0.22435826  0.14266061 ...  1.07954505 -0.4064118
  0.44549515]

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [98]:
import seaborn as sns
import pandas as pd

df=sns.load_dataset("tips")

df['tip_percentage'] = (df['tip'] / df['total_bill']) * 100

grouped = df.groupby(['day', 'time'])['total_bill'].sum()
print(grouped)Weekend dinner segments generate the highest revenue; this insight helps businesses optimize operations, and ML models use such patterns to improve predictions and customer segmentation.


 dinner in weekends generate the highest revenue this insight helps businesses optimize operations, and ML models use such patterns to improve predictions andcustomer segmentation.

day   time
Thur  Lunch     1077.55
      Dinner      18.78
Fri   Lunch       89.92
      Dinner     235.96
Sat   Lunch        0.00
      Dinner    1778.40
Sun   Lunch        0.00
      Dinner    1627.16
Name: total_bill, dtype: float64

C:\Users\giree\AppData\Local\Temp\ipykernel_28248\2045202991.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(['day', 'time'])['total_bill'].sum()